### PR TITLE
Abort build_all if any step fails.

### PR DESCRIPTION
**Pull request by ankurkotwal**

### CODE REVIEW

**Comment by kng** [comment]
Regarding the base image, is there any benefit from this ? I mean, the manual specifically talks about this release and the tools included in it. 

And on the abort on build_all, the specific commands in the scripts also needs this, or depending on a chain of commands to trip.

**Comment by kng** [comment]
These two commits should also not be part of the same MR

**Comment by kng** [comment]
I have included more exit statements in the individual scripts, so the abort on build fail will be accepted if in a separate MR from the base image.

The base image results in spl build failure:
`cmd: ./create_hdr --bin /mnt/u-boot/spl/u-boot-spl.bin --version 0x01010101 --common_hdr u-boot-spl.bin.normal.common.hdr --hdr u-boot-spl.bin.normal.hdr input_files/input_sbl_normal.cfg
./create_hdr: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
`

**Comment by ankurkotwal** [comment]
> Regarding the base image, is there any benefit from this ? I mean, the manual specifically talks about this release and the tools included in it.

I was proposing moving to the updated the base image so that this is being built off a newer toolchain. But I'll admit that I hadn't noticed that the VisionFive 2 docs pointed to bionic being the base. WDYT?

> And on the abort on build_all, the specific commands in the scripts also needs this, or depending on a chain of commands to trip.
> I have included more exit statements in the individual scripts, so the abort on build fail will be accepted if in a separate MR from the base image.

It's good to have the individual scripts bail out on failure but I found that the individual scripts to have dependencies on prior scripts (except the kernel). So if one of the earlier build scripts fail, build_all shouldn't continue.

> These two commits should also not be part of the same MR
That was a mistake on my part. I meant to submit them separately .

**Comment by ankurkotwal** [comment]
Abandoning this PR as it combined two changes.

**Comment by kng** [comment]
> I was proposing moving to the updated the base image so that this is being built off a newer toolchain. But I'll admit that I hadn't noticed that the VisionFive 2 docs pointed to bionic being the base. WDYT?

I tried building the kernel on newer toolchain, but that also means that it can easily be built on modern OS so no real need for this container solution. So it will stay on bionic until they decide to upgrade. It is basically why this repo exist (:

**Pull request closed without merging**
